import { useEffect, useState, type FormEvent } from 'react';
import api from '../api/client';
import type { Category, Order, Product } from '../types';

const blank = { name:'', description:'', price:'', image:'', unit:'item', stock:'0', category:'' };
export default function AdminPage(){
  const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [form,setForm]=useState(blank);
  const load=async()=>{const [p,c,o]=await Promise.all([api.get('/products?limit=100'),api.get('/categories'),api.get('/orders')]);setProducts(p.data.products);setCategories(c.data);setOrders(o.data)};
  useEffect(()=>{load()},[]);
  const createProduct=async(e:FormEvent)=>{e.preventDefault();await api.post('/products',{...form,price:Number(form.price),stock:Number(form.stock)});setForm(blank);await load()};
  const createCategory=async()=>{const name=prompt('Category name'); if(name){await api.post('/categories',{name});await load()}};
  return <section className="page-wrap"><div className="page-heading"><div><span className="eyebrow">Administration</span><h1>Store dashboard</h1><p>Manage inventory, categories and customer orders.</p></div><button className="secondary-btn" onClick={createCategory}>+ Category</button></div><div className="admin-stats"><div><span>Products</span><strong>{products.length}</strong></div><div><span>Categories</span><strong>{categories.length}</strong></div><div><span>Orders</span><strong>{orders.length}</strong></div></div><div className="admin-grid"><form className="panel" onSubmit={createProduct}><h2>Add grocery</h2><input placeholder="Name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea placeholder="Description" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="field-row"><input placeholder="Price" type="number" min="0" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="Stock" type="number" min="0" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></div><input placeholder="Unit e.g. 1 kg" required value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><input placeholder="Image URL" required value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Choose category</option>{categories.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select><button className="primary-btn">Add product</button></form><div className="panel"><h2>Recent orders</h2>{orders.slice(0,8).map(o=><div className="admin-order" key={o._id}><div><strong>#{o._id.slice(-6).toUpperCase()}</strong><span>Rs. {o.total.toLocaleString()}</span></div><select value={o.status} onChange={async e=>{await api.patch(`/orders/${o._id}/status`,{status:e.target.value});await load()}}><option>pending</option><option>confirmed</option><option>packed</option><option>out-for-delivery</option><option>delivered</option><option>cancelled</option></select></div>)}</div></div><div className="panel inventory-panel"><h2>Inventory</h2>{products.map(p=><div className="inventory-row" key={p._id}><img src={p.image}/><span>{p.name}</span><b>Rs. {p.price.toLocaleString()}</b><small>{p.stock} in stock</small><button className="danger-link" onClick={async()=>{if(confirm(`Delete ${p.name}?`)){await api.delete(`/products/${p._id}`);await load()}}}>Delete</button></div>)}</div></section>
}
