import 'dotenv/config';import {connectDB} from '../src/config/db.js';import User from '../src/models/User.js';import Category from '../src/models/Category.js';import Product from '../src/models/Product.js';import Cart from '../src/models/Cart.js';import Order from '../src/models/Order.js';import Review from '../src/models/Review.js';
await connectDB();await Promise.all([Cart.deleteMany({}),Order.deleteMany({}),Review.deleteMany({}),Product.deleteMany({}),Category.deleteMany({}),User.deleteMany({})]);
await User.create([{name:'FreshBasket Admin',email:'admin@freshbasket.com',password:'Admin123!',role:'admin'},{name:'Demo Customer',email:'user@freshbasket.com',password:'User123!',role:'user'}]);
const cats=await Category.insertMany([{name:'Fresh Produce',slug:'fresh-produce'},{name:'Bakery',slug:'bakery'},{name:'Dairy & Eggs',slug:'dairy-eggs'},{name:'Pantry',slug:'pantry'}]);
const by=(name:string)=>cats.find(c=>c.name===name)!._id;
await Product.insertMany([
{name:'Bananas',description:'Naturally sweet ripe bananas for snacks and smoothies.',price:280,image:'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=900&q=80',unit:'1 kg',stock:45,featured:true,category:by('Fresh Produce')},
{name:'Red Apples',description:'Crisp red apples with a balanced sweet-tart flavor.',price:520,image:'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=900&q=80',unit:'1 kg',stock:32,featured:true,category:by('Fresh Produce')},
{name:'Strawberries',description:'Bright, juicy strawberries packed for same-day freshness.',price:690,image:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&q=80',unit:'500 g',stock:18,featured:true,category:by('Fresh Produce')},
{name:'Broccoli',description:'Fresh green broccoli florets for roasting, steaming or salads.',price:360,image:'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=900&q=80',unit:'500 g',stock:24,featured:false,category:by('Fresh Produce')},
{name:'Artisan Bread',description:'Crusty daily-baked loaf with a soft airy center.',price:420,image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80',unit:'1 loaf',stock:14,featured:true,category:by('Bakery')},
{name:'Farm Eggs',description:'A dozen fresh eggs packed carefully for home delivery.',price:460,image:'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=900&q=80',unit:'12 eggs',stock:28,featured:false,category:by('Dairy & Eggs')},
{name:'Fresh Milk',description:'Full-cream fresh milk for breakfast, tea and cooking.',price:310,image:'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=900&q=80',unit:'1 litre',stock:35,featured:false,category:by('Dairy & Eggs')},
{name:'Basmati Rice',description:'Long-grain basmati rice for everyday meals and biryani.',price:980,image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=900&q=80',unit:'2 kg',stock:40,featured:false,category:by('Pantry')}
]);console.log('Seed complete. Admin: admin@freshbasket.com / Admin123! | User: user@freshbasket.com / User123!');process.exit(0);
